argument_specs:
    main:
        options:
            image_version:
                # line 10 of aws/defaults/main.yml
                required: true
                description: "Verison of the Image"
                type: "str"
            publicIP:
                # line 12 of aws/defaults/main.yml
                required: true
                description: "Name of the Public IP."
                type: "str"
            public_ip_address_name:
                # line 13 of aws/defaults/main.yml
                required: true
                description: "Name of the Public IP address name"
                type: "str"
            domain_name:
                # line 14 of aws/defaults/main.yml
                required: true
                description: "The customizable portion of the FQDN assigned to public IP address. This is an explicit setting. If no value is provided, any existing value will be removed on an existing public IP."
                type: "str"
            privatednszone:
                # line 15 of aws/defaults/main.yml
                required: true
                description: "Name of the private DNS zone."
                type: "str"
            allow_virtual_network_access:
                # line 17 of aws/defaults/main.yml
                default: true
                description: "Allows VMs in the remote VNet to access all VMs in the local VNet."
                type: "bool"
            allow_forwarded_traffic:
                # line 18 of aws/defaults/main.yml
                default: true
                description: "Allows forwarded traffic from the VMs in the remote VNet."
                type: "bool"
            ttl:
                # line 35 of aws/defaults/main.yml
                required: true
                description: "The DNS Time-To-Live (TTL), in seconds."
                type: "int"
            protocol:
                # line 36 of aws/defaults/main.yml
                default: "HTTPS"
                description: "The protocol (HTTP, HTTPS or TCP) used to probe for endpoint health."
                type: "str"
            tolerated_number_of_failures:
                # line 41 of aws/defaults/main.yml
                default: 3
                description: "The number of consecutive failed health check before declaring an endpoint in this profile Degraded after the next failed health check."
                type: "int"
            relative_name:
                # line 43 of aws/defaults/main.yml
                required: true
                description: "The relative DNS name provided by this Traffic Manager profile."
                type: "str"
            record_type:
                # line 44 of aws/defaults/main.yml
                required: true
                description: "The type of record set to create or delete."
                type: "str"
            entry:
                # line 45 of aws/defaults/main.yml
                required: true
                description: "Primary data value for all record types."
                type: "str"
            dns_name:
                # line 46 of aws/defaults/main.yml
                required: false
                description: "Name of the public DNS"
                type: "str"
            vpc:
                # line 49 of aws/defaults/main.yml
                required: true
                description: "dict of regions consisting of lists of VPCs to create"
                type: "dict"
            vm:
                # line 91 of aws/defaults/main.yml
                required: true
                description: "Dictionary to get the details of VM created for the intance"
                type: "list"
            db:
                # line 144 of aws/defaults/main.yml
                required: true
                description: "Dictionary to get the details of Database"
                type: "list"
            db_sku_name:
                # line 167 of aws/defaults/main.yml
                required: true
                description: "The name of the SKU, typically, tier + family + cores, for example B_Gen4_1, GP_Gen5_8."
                type: "str"
            db_sku_tier:
                # line 168 of aws/defaults/main.yml
                required: true
                description: "The tier of the particular SKU."
                type: "str"
            db_storage_mb:
                # line 169 of aws/defaults/main.yml
                required: true
                description: "The size code, to be interpreted by resource as appropriate."
                type: "str"
            db_enforce_ssl:
                # line 170 of aws/defaults/main.yml
                default: true
                description: "Enable SSL enforcement."
                type: "bool"
            db_version:
                # line 171 of aws/defaults/main.yml
                required: true
                description: "Maria DB server version"
                type: "str"
            db_admin_username:
                # line 172 of aws/defaults/main.yml
                required: true
                description: "Maria DB username"
                type: "str"
            db_admin_password:
                # line 173 of aws/defaults/main.yml
                required: true
                description: "Maria DB password"
                type: "str"
            managed_mariadb:
                required: true
                description: "Choice of using managed MariaDB"
                type: "bool"

