---
collections:
  - name: redhat.redhat_csp_download
    version: ">=1.2.2"
  - name: redhat.amq_broker
    version: ">=1.1.0"
  - name: redhat.eap
    version: ">=1.2.0"
  - name: middleware_automation.jcliff
    version: ">=0.0.23"
  - name: community.general
  - name: community.mysql
  - name: ansible.netcommon
  - name: ansible.posix
  - name: community.aws
  - name: amazon.aws
