---
- name: Gather information about a particular VPC using VPC name
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_data.name }}"
      "tag:Environment": "crossdc-rhsso-demo"
      "tag:Application": "rhsso"
      "tag:Created-By": "ansible"
  register: vpc_info

- debug:
    var: vpc_info

- name: Gather information about VPC subnets
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: subnet_info

- name: Remove subnets
  ec2_vpc_subnet:
    cidr: "{{ subnet.cidr_block }}"
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
    region: "{{ region }}"
    state: absent
    wait: yes
  loop: "{{ subnet_info.subnets }}"
  loop_control:
    loop_var: subnet

- name: Tear down VPC
  ec2_vpc_net:
    cidr_block: "{{ vpc_info.vpcs[0].cidr_block }}"
    name: "{{ vpc_data.name }}"
    region: "{{ region }}"
    state: absent
