---
- name: Playbook for loadbalancer Hosts
  hosts: loadbalancer
  become: true
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - certificates
    - redhat_csp_download
    - jbcs
  pre_tasks:
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
    - name: Set nid_enabled flag on and keep it persistent across reboots
      ansible.posix.seboolean:
        name: nis_enabled
        state: yes
        persistent: yes