---
- name: Playbook for installing prerequisites
  hosts: all
  tasks:
    - name: "Install packages"
      ansible.builtin.include_role:
        name: fastpackages
      vars:
        packages_list:
          - procps-ng
          - mailcap
          - unzip
          - firewalld
          - ca-certificates
          - python3-lxml
          - "{{ jvm_package }}"
    - name: "Set FQDN"
      ansible.builtin.command: "hostnamectl set-hostname --static {{ inventory_hostname }}{{ domain_name }}"
      become: yes
