---
wildfly_install_workdir: /opt/
wildfly_config_base: standalone-full-ha.xml
wildfly_home: /opt/jboss-eap-7.4/
wildfly_instance_name: "{{ inventory_hostname }}"
app:
  name: 'info-1.1.war'
  url: 'https://drive.google.com/uc?export=download&id=1w9ss5okctnjUvRAxhPEPyC7DmbUwmbhb'
