---
eap_config_base: standalone-full-ha.xml
eap_instance_name: "{{ inventory_hostname }}"
eap_user: wildfly
eap_home: /opt/jboss_eap/jboss-eap-7.4/
eap_java_package_name: java-11-openjdk-headless
eap_java_opts: ''
eap_multicast_addr: 224.0.1.105
eap_bind_addr_private: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address | default('0.0.0.0') }}"
eap_apply_cp: True
eap_systemd_enable: True
eap_enable_yml_config: True
eap_no_restart_after_patch: True
eap_statistics_enabled: True
eap_offline_install: True