---
wildfly_install_workdir: /opt/
wildfly_config_base: standalone-full-ha.xml
wildfly_home: /opt/jboss-eap-7.4/
wildfly_instance_name: "{{ inventory_hostname }}"
wildfly_java_package_name: java-11-openjdk-headless
wildfly_multicast_addr: 224.0.1.105
wildfly_bind_addr_private: 0.0.0.0
app:
  name: 'info-1.1.war'
  url: 'https://drive.google.com/uc?export=download&id=1w9ss5okctnjUvRAxhPEPyC7DmbUwmbhb'
